"""empty message

Revision ID: 3c07769764af
Revises: None
Create Date: 2017-02-19 09:20:43.191342

"""

# revision identifiers, used by Alembic.
revision = '3c07769764af'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
