"""empty message

Revision ID: 58df6f99be28
Revises: 3c07769764af
Create Date: 2017-03-26 21:38:46.087743

"""

# revision identifiers, used by Alembic.
revision = '58df6f99be28'
down_revision = '3c07769764af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('projects', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('publications', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('research', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'research')
    op.drop_column('users', 'publications')
    op.drop_column('users', 'projects')
    ### end Alembic commands ###
